# Generated by Django 4.2.27 on 2026-01-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(blank=True, help_text='Emoji flag or similar', max_length=10, null=True)),
                ('background_image', models.ImageField(upload_to='countries/')),
                ('intro', models.TextField()),
                ('facts', models.JSONField(default=list, help_text='List of facts')),
                ('universities', models.JSONField(default=list, help_text='List of top universities')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='downloads/')),
                ('file_type', models.CharField(help_text='PDF, DOCX etc.', max_length=10)),
                ('icon_class', models.CharField(default='fa-file-arrow-down', max_length=50)),
                ('size_label', models.CharField(help_text='e.g. 4.5 MB', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part1', models.CharField(default='Dream Big.', max_length=100)),
                ('title_part2', models.CharField(default='Study Global.', max_length=100)),
                ('subtitle', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='FontAwesome class e.g., fa-compass', max_length=50)),
                ('intro', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of features')),
                ('process', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(help_text='Short name e.g., IELTS', max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(max_length=50)),
                ('intro', models.TextField()),
                ('format_data', models.JSONField(default=list, help_text='List of format sections')),
                ('score_scale', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
