# Generated by Django 4.2.27 on 2026-01-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feature_stat_alter_country_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GSREC NEPAL', max_length=100)),
                ('logo', models.ImageField(help_text='Upload logo image', upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Upload favicon', null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
