# Generated by Django 4.2.27 on 2026-01-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GSREC NEPAL', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Main logo for Header', null=True, upload_to='site/')),
                ('footer_logo', models.ImageField(blank=True, help_text='Logo for Footer. Defaults to main logo if not set.', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
