# Generated by Django 4.2.27 on 2026-01-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_delete_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About GSREC Nepal', max_length=100)),
                ('subtitle', models.CharField(default='Global Student Recruitment & Education Consultancy (GSREC)', max_length=200)),
                ('main_image', models.ImageField(blank=True, help_text='Main image for About Us page', null=True, upload_to='about/')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_description', models.TextField(default='At GSREC Nepal, based in Putalisadak, Kathmandu, we are committed to providing genuine and professional guidance to students aspiring to study abroad.')),
                ('stat1_number', models.CharField(default='5000+', help_text='e.g. 5000+', max_length=20)),
                ('stat1_label', models.CharField(default='Students Placed', max_length=50)),
                ('stat2_number', models.CharField(default='98%', help_text='e.g. 98%', max_length=20)),
                ('stat2_label', models.CharField(default='Visa Success Rate', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'About Us Page',
            },
        ),
    ]
