# Generated by Django 4.2.27 on 2026-01-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(help_text='Content for the page (HTML supported)')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='resources/')),
                ('file_type', models.CharField(help_text='PDF, DOCX etc.', max_length=10)),
                ('icon_class', models.CharField(default='fa-file-arrow-down', max_length=50)),
                ('size_label', models.CharField(help_text='e.g. 4.5 MB', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Download',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='New Baneshwor, Kathmandu, Nepal', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='info@gsrecnepal.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(blank=True, default='Global Student Research & Educational Consultancy (GSREC Nepal) is a leading educational consultancy in Nepal, dedicated to providing ethical and reliable counseling services to students.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+977 1-4244XXX', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
