# Generated by Django 4.2.27 on 2026-01-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_legalpage_resource_delete_download_and_more'),
    ]

    operations = [
    ]
