# Generated by Django 4.2.27 on 2026-01-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20260114_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get In Touch', max_length=100)),
                ('subtitle', models.CharField(default='Visit our office in Kathmandu or send us a message.', max_length=200)),
                ('info_panel_title', models.CharField(default="Let's talk about your future", max_length=100)),
                ('map_iframe_url', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d267.59968535258844!2d85.33460729358669!3d27.69097844872121!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb19962c4fdda5%3A0x65fa64aee5d96afa!2sGlobal%20Social%20Research%20and%20Educational%20Consultancy%20P.%20Ltd.!5e0!3m2!1sen!2snp!4v1768297945353!5m2!1sen!2snp', help_text='Google Maps Embed URL (src attribute)')),
                ('map_link', models.URLField(default='https://maps.app.goo.gl/JQTJ6DAPSxmNNJUA8', help_text='Direct link to Google Maps')),
            ],
            options={
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_title', models.CharField(default='Your Journey to Success', max_length=100)),
                ('journey_subtitle', models.CharField(default='We guide you through every step of your study abroad dream.', max_length=200)),
                ('cta_title', models.CharField(default='Ready to start your journey?', max_length=100)),
                ('cta_subtitle', models.CharField(default='Book a free counseling session today.', max_length=200)),
                ('cta_button_text', models.CharField(default='Contact Us Now', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='FontAwesome class e.g. fa-comments', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations_title', models.CharField(default='All Study Destinations', max_length=100)),
                ('destinations_subtitle', models.TextField(default='Explore the best countries for international education. We provide end-to-end support.')),
                ('services_title', models.CharField(default='Our Expert Services', max_length=100)),
                ('test_prep_title', models.CharField(default='Standardized Test Preparation', max_length=100)),
                ('resources_title', models.CharField(default='Resources Center', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Listing Page Settings',
            },
        ),
    ]
