# Generated by Django 4.2.27 on 2026-01-14 05:16

from django.db import migrations


def seed_content(apps, schema_editor):
    ContactPage = apps.get_model('core', 'ContactPage')
    HomePageSettings = apps.get_model('core', 'HomePageSettings')
    JourneyStep = apps.get_model('core', 'JourneyStep')
    ListingPageSettings = apps.get_model('core', 'ListingPageSettings')

    ContactPage.objects.get_or_create(id=1)
    HomePageSettings.objects.get_or_create(id=1)
    ListingPageSettings.objects.get_or_create(id=1)

    steps = [
        ('Counseling', 'Expert guidance to identify your goals and match you with the right course.', 'fa-comments', 1),
        ('University Selection', 'Choose from 500+ top universities that align with your aspirations.', 'fa-university', 2),
        ('Documentation', 'Full assistance with applications, SOPs, and financial documents.', 'fa-file-contract', 3),
        ('Visa Success', 'Rigorous interview prep and visa lodging for high success rates.', 'fa-brands fa-cc-visa', 4),
        ('Fly Abroad', 'Pre-departure support to ensure you settle in smoothly.', 'fa-plane-departure', 5),
    ]
    for title, desc, icon, order in steps:
        JourneyStep.objects.get_or_create(title=title, description=desc, icon_class=icon, order=order)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactpage_homepagesettings_journeystep_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_content),
    ]
