# Generated by Django 4.2.27 on 2026-01-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20260114_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='destinations_subtitle',
            field=models.CharField(default="Choose from the world's top study destinations. We guide you to the perfect country for your career goals.", max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='destinations_title',
            field=models.CharField(default='Popular Destinations', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='features_subtitle',
            field=models.CharField(default='We are not just consultants; we are your career architects. Trusted by students across Nepal.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='features_title',
            field=models.CharField(default='Why Choose GSREC Nepal?', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partners_subtitle',
            field=models.CharField(default='Collaborating with world-class universities and institutions globally.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='partners_title',
            field=models.CharField(default='Our Trusted Partners', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='services_subtitle',
            field=models.CharField(default='Comprehensive guidance at every step of your study abroad journey.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='services_title',
            field=models.CharField(default='Our Services', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonials_subtitle',
            field=models.CharField(default='Hear from students who made their dreams come true with GSREC.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='testimonials_title',
            field=models.CharField(default='Student Stories', max_length=100),
        ),
    ]
