# Generated by Django 4.2.27 on 2026-01-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_homepagesettings_destinations_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpagesettings',
            name='resources_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listingpagesettings',
            name='services_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listingpagesettings',
            name='success_stories_subtitle',
            field=models.TextField(default='Hear from our students who are now studying at their dream universities across the globe.'),
        ),
        migrations.AddField(
            model_name='listingpagesettings',
            name='success_stories_title',
            field=models.CharField(default='Success Stories', max_length=100),
        ),
        migrations.AddField(
            model_name='listingpagesettings',
            name='test_prep_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
    ]
