# Generated by Django 4.2.27 on 2026-01-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_listingpagesettings_resources_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_company_title',
            field=models.CharField(default='Company', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_title',
            field=models.CharField(default='Contact', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_destinations_title',
            field=models.CharField(default='Destinations', max_length=50),
        ),
    ]
