# Generated by Django 4.2.27 on 2026-01-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_testimonial_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_link',
            field=models.URLField(blank=True, help_text='Direct Google Maps link for the address', null=True),
        ),
    ]
