# Generated by Django 4.2.27 on 2026-01-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_testimonial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testprep',
            name='icon_class',
            field=models.CharField(help_text="Full FontAwesome class, e.g., 'fa-solid fa-book' or 'fa-brands fa-duolingo'", max_length=50),
        ),
    ]
