# Generated by Django 4.2.27 on 2026-01-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_testprep_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
